"""add role to customer

Revision ID: 2fa6ba1ec3d9
Revises: fb42075ffc7b
Create Date: 2024-05-23 10:43:41.991545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa6ba1ec3d9'
down_revision = 'fb42075ffc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_foreign_key('customer_role_id_fkey', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customer_role_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###
