from marshmallow import fields, validate
from schemas import ma

class ProductSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True, validate=validate.Length(min=5, max=20)) # Product name must be between 5 and 20 characters
    price = fields.Float(required=True, validate=validate.Range(min=0)) # Product price must be >= 0

product_schema = ProductSchema()
products_schema = ProductSchema(many=True) # for handling multiple products